ALTER TYPE "public"."ComplaintStatus" ADD VALUE IF NOT EXISTS 'TRIAGE';
ALTER TYPE "public"."ComplaintStatus" ADD VALUE IF NOT EXISTS 'DRAFT_RESPONSE';
ALTER TYPE "public"."ComplaintStatus" ADD VALUE IF NOT EXISTS 'QA_LEGAL_REVIEW';
ALTER TYPE "public"."ComplaintStatus" ADD VALUE IF NOT EXISTS 'RESPONSE_ISSUED';
ALTER TYPE "public"."ComplaintStatus" ADD VALUE IF NOT EXISTS 'AWAITING_FEEDBACK';
ALTER TYPE "public"."ComplaintStatus" ADD VALUE IF NOT EXISTS 'APPEAL';

