services:
  api:
    build: ../../apps/api
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://mopd_cms:mopd_cms_dev_2026!@postgres:5432/mopd_cms
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: minio
      MINIO_PORT: "9000"

  web:
    build: ../../apps/web
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mopd_cms
      POSTGRES_USER: mopd_cms
      POSTGRES_PASSWORD: mopd_cms_dev_2026!
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  clamav:
    image: clamav/clamav:latest
    volumes:
      - clamdata:/var/lib/clamav

volumes:
  pgdata:
  redisdata:
  miniodata:
  clamdata:
